# Generated by Django 4.2.20 on 2025-05-05 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolios", "0002_add_ai_generated_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfoliomaterial",
            name="is_class_material",
            field=models.BooleanField(default=True, verbose_name="Material de Clase"),
        ),
    ]
