# Generated by Django 4.2.20 on 2025-04-17 23:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "code",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="El código modular debe tener 7 dígitos",
                                regex="^[0-9]{7}$",
                            )
                        ],
                        verbose_name="código modular",
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        help_text="Este será el subdominio para la institución (ejemplo: miescuela)",
                        max_length=100,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="El dominio solo puede contener letras minúsculas y números",
                                regex="^[a-z0-9]+$",
                            )
                        ],
                        verbose_name="dominio",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="institutions/logos/",
                        verbose_name="logo",
                    ),
                ),
                ("address", models.CharField(max_length=200, verbose_name="Dirección")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Teléfono"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Correo electrónico"
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="Sitio web")),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "school_director",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_institution",
                        to="accounts.director",
                    ),
                ),
            ],
            options={
                "verbose_name": "Institución",
                "verbose_name_plural": "Instituciones",
            },
        ),
        migrations.CreateModel(
            name="InstitutionSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "academic_year_start",
                    models.DateField(verbose_name="inicio del año académico"),
                ),
                (
                    "academic_year_end",
                    models.DateField(verbose_name="fin del año académico"),
                ),
                (
                    "enable_portfolio",
                    models.BooleanField(
                        default=True, verbose_name="habilitar portafolios"
                    ),
                ),
                (
                    "enable_ai_content",
                    models.BooleanField(
                        default=True, verbose_name="habilitar contenido IA"
                    ),
                ),
                (
                    "logo_enabled",
                    models.BooleanField(
                        default=True, verbose_name="mostrar logo en plataforma"
                    ),
                ),
                (
                    "custom_theme",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="tema personalizado"
                    ),
                ),
                (
                    "institution",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="institutions.institution",
                    ),
                ),
            ],
            options={
                "verbose_name": "configuración de institución",
                "verbose_name_plural": "configuraciones de instituciones",
            },
        ),
        migrations.CreateModel(
            name="Director",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dni",
                    models.CharField(max_length=8, unique=True, verbose_name="DNI"),
                ),
                ("phone", models.CharField(max_length=15, verbose_name="teléfono")),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "institution",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="director",
                        to="institutions.institution",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="director_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "director",
                "verbose_name_plural": "directores",
            },
        ),
    ]
