# Generated by Django 4.2.10 on 2025-06-01 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='institution',
            name='established_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Año de Fundación'),
        ),
        migrations.AddField(
            model_name='institution',
            name='mission',
            field=models.TextField(blank=True, null=True, verbose_name='Misión'),
        ),
        migrations.AddField(
            model_name='institution',
            name='type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tipo de Educación'),
        ),
        migrations.AddField(
            model_name='institution',
            name='vision',
            field=models.TextField(blank=True, null=True, verbose_name='Visión'),
        ),
        migrations.AddField(
            model_name='institutionsettings',
            name='accent_color',
            field=models.CharField(default='#00CFFF', help_text='Color de acento de la institución (formato: #RRGGBB)', max_length=7, verbose_name='Color de Acento'),
        ),
        migrations.AddField(
            model_name='institutionsettings',
            name='primary_color',
            field=models.CharField(default='#005CFF', help_text='Color principal de la institución (formato: #RRGGBB)', max_length=7, verbose_name='Color Primario'),
        ),
        migrations.AddField(
            model_name='institutionsettings',
            name='secondary_color',
            field=models.CharField(default='#A142F5', help_text='Color secundario de la institución (formato: #RRGGBB)', max_length=7, verbose_name='Color Secundario'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='address',
            field=models.CharField(blank=True, max_length=200, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='institutionsettings',
            name='academic_year_end',
            field=models.DateField(blank=True, null=True, verbose_name='fin del año académico'),
        ),
        migrations.AlterField(
            model_name='institutionsettings',
            name='academic_year_start',
            field=models.DateField(blank=True, null=True, verbose_name='inicio del año académico'),
        ),
    ]
