version: '3.8'

services:
  # Base de datos PostgreSQL
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: edugen
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: EduGen123!
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Cache Redis
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  

  # Aplicación Django
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      # Configuración de base de datos
      PGHOST: db
      PGPORT: 5432
      PGDATABASE: edugen
      PGUSER: postgres
      PGPASSWORD: EduGen123!
      
      # Configuración de Redis
      REDIS_URL: redis://redis:6379/0
      
      # Configuración de Django
      DJANGO_SETTINGS_MODULE: config.settings.production
      DEBUG: "False"
      SECRET_KEY: "django-insecure-edugen-docker-key-2024-change-in-production-f8k9j2h3g4"
      ALLOWED_HOSTS: "localhost,127.0.0.1,0.0.0.0,edugen-app.azurewebsites.net"
      
      # Configuración de Google OAuth
      SOCIAL_AUTH_GOOGLE_OAUTH2_KEY: "50661052209-7g0jf8e59ea1tme1sqaa80mgouibuj01.apps.googleusercontent.com"
      SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET: "AIzaSyDbaO4sVGS5_dCMV1r4yizjzqAoakAnME0"
      
      # Configuración de IA
      DEEPSEEK_API_KEY: "sk-f1bfb13127b14daf97788bb0232a5584"
      AI_PROVIDER: deepseek
      
      # Configuración adicional
      WEBSITE_HOSTNAME: "localhost:8000"
      CSRF_TRUSTED_ORIGINS: "http://localhost:8000,https://localhost:8000"
      
    volumes:
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
      - ./logs:/app/logs
    depends_on:
      - db
      - redis
    restart: unless-stopped

  # Nginx (opcional para producción)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./staticfiles:/app/staticfiles:ro
      - ./media:/app/media:ro
    depends_on:
      - web
    restart: unless-stopped
    profiles:
      - production

volumes:
  postgres_data:
  redis_data: 