# Generated by Django 4.2.20 on 2025-04-17 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ai_content_generator", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SCORMPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "standard",
                    models.CharField(
                        choices=[
                            ("scorm_1.2", "SCORM 1.2"),
                            ("scorm_2004_3rd", "SCORM 2004 3rd Edition"),
                            ("scorm_2004_4th", "SCORM 2004 4th Edition"),
                        ],
                        default="scorm_2004_4th",
                        max_length=20,
                    ),
                ),
                ("package_file", models.FileField(upload_to="scorm_packages/")),
                ("manifest_file", models.TextField(blank=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("is_published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_scorm_packages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "generated_content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scorm_packages",
                        to="ai_content_generator.generatedcontent",
                    ),
                ),
            ],
        ),
    ]
