# Generated by Django 4.2.10 on 2025-06-08 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0004_coursetopic"),
        ("portfolios", "0004_fix_is_class_material"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfoliomaterial",
            name="course_topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="materials",
                to="academic.coursetopic",
                verbose_name="Tema de Curso",
            ),
        ),
    ]
