# Generated by Django 4.2.10 on 2025-06-04 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_content_generator', '0004_alter_contentrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentrequest',
            name='for_class',
            field=models.BooleanField(default=False, help_text='Indica si el contenido es para toda la clase o individual'),
        ),
        migrations.AddIndex(
            model_name='contentrequest',
            index=models.Index(fields=['for_class'], name='ai_content__for_cla_3b1e6e_idx'),
        ),
    ]
