# Generated by Django 4.2.20 on 2025-04-17 23:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("due_date", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "max_score",
                    models.DecimalField(decimal_places=2, default=20.0, max_digits=5),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nombre del curso"),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Código"),
                ),
                (
                    "description",
                    models.TextField(
                        default="Sin descripción", verbose_name="Descripción"
                    ),
                ),
                ("credits", models.IntegerField(default=3, verbose_name="Créditos")),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Curso",
                "verbose_name_plural": "Cursos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CourseAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hours_per_week",
                    models.PositiveIntegerField(
                        default=4, verbose_name="Horas semanales"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Asignación de Curso",
                "verbose_name_plural": "Asignaciones de Cursos",
                "ordering": ["section", "course"],
            },
        ),
        migrations.CreateModel(
            name="CourseMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="course_materials/%Y/%m/",
                        verbose_name="Archivo",
                    ),
                ),
                (
                    "material_type",
                    models.CharField(
                        choices=[
                            ("PRESENTACION", "Presentación"),
                            ("GUIA", "Guía de estudio"),
                            ("TAREA", "Tarea"),
                            ("EXAMEN", "Examen"),
                            ("LECTURA", "Lectura"),
                            ("VIDEO", "Video"),
                            ("AUDIO", "Audio"),
                            ("OTRO", "Otro"),
                        ],
                        default="OTRO",
                        max_length=20,
                        verbose_name="Tipo de Material",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Material de Curso",
                "verbose_name_plural": "Materiales de Curso",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(
                        default="2025", max_length=9, verbose_name="Año Académico"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Activo"),
                            ("WITHDRAWN", "Retirado"),
                            ("SUSPENDED", "Suspendido"),
                            ("GRADUATED", "Graduado"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "enrollment_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de Matrícula",
                    ),
                ),
                (
                    "withdrawal_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Retiro"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observaciones")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Matrícula",
                "verbose_name_plural": "Matrículas",
                "ordering": ["-enrollment_date"],
            },
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Nombre")),
                (
                    "level",
                    models.CharField(
                        choices=[("SECUNDARIA", "Secundaria")],
                        default="SECUNDARIA",
                        max_length=50,
                        verbose_name="Nivel",
                    ),
                ),
                (
                    "description",
                    models.TextField(default="", verbose_name="Descripción"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Grado",
                "verbose_name_plural": "Grados",
                "ordering": ["level", "name"],
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1, verbose_name="Nombre")),
                (
                    "capacity",
                    models.PositiveIntegerField(default=30, verbose_name="Capacidad"),
                ),
                (
                    "current_students",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Estudiantes Actuales"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Sección",
                "verbose_name_plural": "Secciones",
                "ordering": ["grade", "name"],
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dni",
                    models.CharField(max_length=8, unique=True, verbose_name="DNI"),
                ),
                ("birth_date", models.DateField(verbose_name="fecha de nacimiento")),
                ("address", models.TextField(blank=True, verbose_name="dirección")),
                (
                    "guardian_name",
                    models.CharField(
                        max_length=200, verbose_name="nombre del apoderado"
                    ),
                ),
                (
                    "guardian_phone",
                    models.CharField(
                        max_length=15, verbose_name="teléfono del apoderado"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "estudiante",
                "verbose_name_plural": "estudiantes",
            },
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dni",
                    models.CharField(max_length=8, unique=True, verbose_name="DNI"),
                ),
                (
                    "speciality",
                    models.CharField(
                        choices=[
                            ("MAT", "Matemática"),
                            ("COM", "Comunicación"),
                            ("CTA", "Ciencia y Tecnología"),
                            ("SOC", "Ciencias Sociales"),
                            ("ING", "Inglés"),
                            ("ART", "Arte y Cultura"),
                            ("EFI", "Educación Física"),
                        ],
                        max_length=3,
                        verbose_name="especialidad",
                    ),
                ),
                (
                    "teacher_code",
                    models.CharField(
                        default="DOC-00000", editable=False, max_length=10, unique=True
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        default="000000000", max_length=9, verbose_name="teléfono"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="dirección"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "profesor",
                "verbose_name_plural": "profesores",
            },
        ),
    ]
