# Generated by Django 5.1.7 on 2025-05-08 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="google_account",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="cuenta de Google"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="google_account_linked",
            field=models.BooleanField(
                default=False, verbose_name="cuenta Google vinculada"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="google_linked_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="fecha de vinculación"
            ),
        ),
    ]
