# Generated by Django 4.2.10 on 2025-06-01 03:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic', '0003_student_google_account_student_google_account_linked_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Tema')),
                ('description', models.TextField(blank=True, verbose_name='Descripción del Tema')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='academic.course', verbose_name='Curso')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_course_topics', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_topics', to='academic.section', verbose_name='Sección')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_topics', to='academic.teacher', verbose_name='Profesor')),
            ],
            options={
                'verbose_name': 'Tema de Curso',
                'verbose_name_plural': 'Temas de Curso',
                'ordering': ['course', 'section', 'created_at'],
                'unique_together': {('course', 'section', 'title')},
            },
        ),
    ]
