# Generated by Django 4.2.20 on 2025-04-19 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContenidoInteractivo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("titulo", models.CharField(max_length=255, verbose_name="Título")),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                ("prompt_original", models.TextField(verbose_name="Prompt Original")),
                (
                    "contenido_ai_original",
                    models.TextField(verbose_name="Contenido IA Original"),
                ),
                (
                    "contenido_html",
                    tinymce.models.HTMLField(verbose_name="Contenido HTML Editado"),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("publicado", "Publicado"),
                            ("archivado", "Archivado"),
                        ],
                        default="borrador",
                        max_length=20,
                    ),
                ),
                (
                    "convertido_scorm",
                    models.BooleanField(
                        default=False, verbose_name="Convertido a SCORM"
                    ),
                ),
                (
                    "paquete_scorm",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="scorm_packages/",
                        verbose_name="Paquete SCORM",
                    ),
                ),
                (
                    "etiquetas",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Etiquetas"
                    ),
                ),
                (
                    "nivel_educativo",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Nivel Educativo",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contenidos_creados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contenido Interactivo",
                "verbose_name_plural": "Contenidos Interactivos",
                "ordering": ["-fecha_actualizacion"],
            },
        ),
        migrations.CreateModel(
            name="ContenidoRecurso",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("titulo", models.CharField(max_length=255, verbose_name="Título")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("imagen", "Imagen"),
                            ("video", "Video"),
                            ("documento", "Documento"),
                            ("link", "Enlace"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de recurso",
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="recursos/",
                        verbose_name="Archivo",
                    ),
                ),
                ("url", models.URLField(blank=True, null=True, verbose_name="URL")),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                ("orden", models.IntegerField(default=0, verbose_name="Orden")),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "contenido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recursos",
                        to="content.contenidointeractivo",
                        verbose_name="Contenido relacionado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recurso de Contenido",
                "verbose_name_plural": "Recursos de Contenido",
                "ordering": ["orden", "titulo"],
            },
        ),
    ]
