# Generated by Django 4.2.20 on 2025-04-17 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ai_content_generator", "0001_initial"),
        ("portfolios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentrequest",
            name="related_topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="content_requests",
                to="portfolios.portfoliotopic",
            ),
        ),
        migrations.AddField(
            model_name="contentrequest",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="content_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="generatedcontent",
            index=models.Index(
                fields=["request"], name="ai_content__request_93a1d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentrequest",
            index=models.Index(
                fields=["teacher"], name="ai_content__teacher_dee29b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentrequest",
            index=models.Index(
                fields=["course"], name="ai_content__course__c345d3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentrequest",
            index=models.Index(fields=["status"], name="ai_content__status_af0363_idx"),
        ),
    ]
