# Generated by Django 5.1.7 on 2025-04-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_content_generator', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrapesJSTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='templates/thumbnails/')),
                ('html_content', models.TextField()),
                ('css_content', models.TextField(blank=True)),
                ('js_content', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
