# Generated by Django 5.1.7 on 2025-05-08 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_content_generator", "0003_grapesjstemplate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendiente"),
                    ("processing", "Procesando"),
                    ("completed", "Completado"),
                    ("failed", "Fallido"),
                    ("cancelled", "Cancelado"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
